[package]
name = "transybot"
version = "0.1.0"
authors = ["Connie Hilarides <conni_h@outlook.com>"]
edition = "2018"

[dependencies]
diesel = { version="1.4.2", features = ["sqlite"] }
dotenv = "0.14.1"
serenity = "0.7.0"
